### ISSUE TITLE
Adding a Pull Request and Issue Template

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/2014.fossasia.org#14]
We should add **Pull Request** and **Issue** template, as in other **@fossasia** repo's.

![GCI_TASK](https://img.shields.io/badge/gciTask-Additional-blue.svg)

**Comment by mariobehling** [comment]
Low priority. We actually need people fixing issues instead of copying templates from one repo to others. This is just a simple website, not a large software application. We just need to get a few things done here.

**Comment by 0x48piraj** [comment]
That's why I added "additional" parameter.
It would not counted as a task. It was just for making the repo look good :smile:
