### ISSUE TITLE
Change header menu bar to FOSSASIA standard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2014.fossasia.org#17]
The top menu bar is very different to the standard FOSSASIA design. Please change it and adapt the sorting of the bar to be more closely to other events.

**Comment by ryushar** [comment]
Working on it!

**Comment by mariobehling** [comment]
Issue still unsolved.

**Comment by samyakbvs** [comment]
claiming

**Comment by abishekvashok** [comment]
@samyakbvs can I work on this?
