### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2014.fossasia.org#18]
Add a standard FOSSASIA Footer.

**Comment by 0x48piraj** [comment]
Claiming :tada:

**Comment by abishekvashok** [comment]
@0x48piraj are u still doing it? Can I do it?

**Comment by 0x48piraj** [comment]
I'm doing it @abishekvashok :+1: 
You can do further changes, as others , I will send a PR today

> I sent one PR but the repo was updated, so .. Again redo the work

**Comment by abishekvashok** [comment]
Any updates @0x48piraj

**Comment by 0x48piraj** [comment]
@duttaditya18 Stopped collaborating with me. will do it myself.

**Comment by ParthS007** [comment]
@0x48piraj Please update your status or let others do it 👍
