### ISSUE TITLE
Avoid dependencies  like maxcdn

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2014.fossasia.org#26]
Please avoid dependencies and take out 

`+	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">`

**Comment by YashKumarVerma** [comment]
working on it

**Comment by nzec** [comment]
Should I work on this @YashKumarVerma ?

**Comment by ParthS007** [comment]
@YashKumarVerma Please update your status on it 👍

**Comment by 0x48piraj** [comment]
@mariobehling Please close this. I eventually *(including earlier Pull Requests too)* removed maxcdn files and replaced it with local css files.
