### ISSUE TITLE
Make site in design of fossasia main site.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2014.fossasia.org#28]
Please make the site look closer to main site.

**Comment by Ploypiti** [comment]
Claiming.

**Comment by abishekvashok** [comment]
@Ploypiti status?

**Comment by Ploypiti** [comment]
@abishekvashok Working on it (tbh I forgot to save the file so I need to restart)

**Comment by kubami9** [comment]
@Ploypiti Can I ask what changes are you working on? I mean there are many things about this website which could be changed and while claiming another issue I wouldn't like to repeat your job

**Comment by Ploypiti** [comment]
@kubami9 Change Fonts & color scheme to normal font used by every Fossasia site, layouts and fix some feature.

**Comment by Ploypiti** [comment]
The CSS doesn't work on the repo & preview while it does on the local host...
![image](https://user-images.githubusercontent.com/32614202/34379355-721be2ec-eb2d-11e7-92f8-662a28611ab4.png)

**Comment by Saichethan** [comment]
What are your specifications you need
