### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/2014.fossasia.org#47]
There is no footer we have add one
I am working on it pls take my permission before working on the issue

**Comment by kubami9** [comment]
@samyakbvs  There is already claimed issue with this task https://github.com/fossasia/2014.fossasia.org/issues/18, please make sure there's no such issue before creating your own

**Comment by nzec** [comment]
Don't make copies of issues.

**Comment by 0x48piraj** [comment]
Thanks @kubami9 :+1: :blush:

**Comment by harshit98** [comment]
Similar to #18. Closing this issue.
